# Config for using theme as Hugo website

BaseURL = 'https://oldnew-mashup.wildtechgarden.ca'
languageCode = 'en-ca'
languageLang = 'en'
title = 'CShore OldNew Mashup Theme Test Site'
enableGitInfo = 'true'
theme = 'github.com/danielfdickinson/netlify-oldnew-mashup'
pygmentsUseClasses = true
pygmentsCodeFences = true
themesDir = "../.."

# RSS, categories and tags disabled for an easy start
# See configuration options for more details:
# https://gohugo.io/getting-started/configuration/#toml-configuration
disableKinds = ['RSS', 'taxonomy', 'taxonomyTerm']

[params]
  siteid = 'OldNew Theme'
  license = 'CC-BY-4.0'
  copyright = '2018,2021 Daniel F. Dickinson'
  pygmentsUsesClasses = true
  pygmentsCodeFences = true

[frontmatter]
lastmod = ["lastmod",":git","date","publishDate"]

[build]
  useResourceCacheWhen = "fallback"
